// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zdravstvo.Infrastructure.Data;

#nullable disable

namespace Zdravstvo.Infrastructure.Migrations
{
    [DbContext(typeof(ZdravstvoContext))]
    [Migration("20251128173710_dijagnozaPregledOneToOne")]
    partial class dijagnozaPregledOneToOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zdravstvo.Core.Entities.Dijagnoza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ICD10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Napomene")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PregledId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PregledId")
                        .IsUnique();

                    b.ToTable("Dijagnoze");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Doktor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojLicence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecijalizacijaId")
                        .HasColumnType("int");

                    b.Property<int>("UstanovaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId")
                        .IsUnique();

                    b.HasIndex("SpecijalizacijaId");

                    b.HasIndex("UstanovaId");

                    b.ToTable("Doktori");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.MedicinskiKarton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alergije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HronicneBolesti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KrvnaGrupa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operacije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PorodicnaAnamneza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terapije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vakcinacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedicinskiKartoni");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Pacijent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("MedicinskiKartonId")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId")
                        .IsUnique();

                    b.HasIndex("MedicinskiKartonId")
                        .IsUnique();

                    b.ToTable("Pacijenti");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Pregled", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPregleda")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<string>("Misljenje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Napomene")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("Terapija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TerminId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoktorId");

                    b.HasIndex("PacijentId");

                    b.HasIndex("TerminId");

                    b.ToTable("Pregledi");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Recepti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Doziranje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivLijeka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PregledId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PregledId");

                    b.ToTable("Recepti");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Specijalizacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Specijalizacija");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumVreme")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UputnicaId")
                        .HasColumnType("int");

                    b.Property<int>("UstanovaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoktorId");

                    b.HasIndex("PacijentId");

                    b.HasIndex("UputnicaId");

                    b.HasIndex("UstanovaId");

                    b.ToTable("Termini");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Uputnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumKoristenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsKoristena")
                        .HasColumnType("bit");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("SifraUputnice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecijalizacijaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoktorId");

                    b.HasIndex("PacijentId");

                    b.HasIndex("SpecijalizacijaId");

                    b.ToTable("Uputnice");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Ustanova", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ustanove");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Dijagnoza", b =>
                {
                    b.HasOne("Zdravstvo.Core.Entities.Pregled", "Pregled")
                        .WithOne("Dijagnoza")
                        .HasForeignKey("Zdravstvo.Core.Entities.Dijagnoza", "PregledId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pregled");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Doktor", b =>
                {
                    b.HasOne("Zdravstvo.Core.Entities.Korisnik", "Korisnik")
                        .WithOne("Doktor")
                        .HasForeignKey("Zdravstvo.Core.Entities.Doktor", "KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zdravstvo.Core.Entities.Specijalizacija", "Specijalizacija")
                        .WithMany()
                        .HasForeignKey("SpecijalizacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zdravstvo.Core.Entities.Ustanova", "Ustanova")
                        .WithMany("Doktori")
                        .HasForeignKey("UstanovaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Specijalizacija");

                    b.Navigation("Ustanova");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Pacijent", b =>
                {
                    b.HasOne("Zdravstvo.Core.Entities.Korisnik", "Korisnik")
                        .WithOne("Pacijent")
                        .HasForeignKey("Zdravstvo.Core.Entities.Pacijent", "KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zdravstvo.Core.Entities.MedicinskiKarton", "MedicinskiKarton")
                        .WithOne()
                        .HasForeignKey("Zdravstvo.Core.Entities.Pacijent", "MedicinskiKartonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("MedicinskiKarton");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Pregled", b =>
                {
                    b.HasOne("Zdravstvo.Core.Entities.Doktor", "Doktor")
                        .WithMany()
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zdravstvo.Core.Entities.Pacijent", "Pacijent")
                        .WithMany()
                        .HasForeignKey("PacijentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zdravstvo.Core.Entities.Termin", "Termin")
                        .WithMany()
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Pacijent");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Recepti", b =>
                {
                    b.HasOne("Zdravstvo.Core.Entities.Pregled", "Pregled")
                        .WithMany()
                        .HasForeignKey("PregledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregled");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Termin", b =>
                {
                    b.HasOne("Zdravstvo.Core.Entities.Doktor", "Doktor")
                        .WithMany("Termini")
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zdravstvo.Core.Entities.Pacijent", "Pacijent")
                        .WithMany("Termini")
                        .HasForeignKey("PacijentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zdravstvo.Core.Entities.Uputnica", "Uputnica")
                        .WithMany()
                        .HasForeignKey("UputnicaId");

                    b.HasOne("Zdravstvo.Core.Entities.Ustanova", "Ustanova")
                        .WithMany("Termini")
                        .HasForeignKey("UstanovaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Pacijent");

                    b.Navigation("Uputnica");

                    b.Navigation("Ustanova");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Uputnica", b =>
                {
                    b.HasOne("Zdravstvo.Core.Entities.Doktor", "Doktor")
                        .WithMany()
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zdravstvo.Core.Entities.Pacijent", "Pacijent")
                        .WithMany()
                        .HasForeignKey("PacijentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zdravstvo.Core.Entities.Specijalizacija", "Specijalizacija")
                        .WithMany()
                        .HasForeignKey("SpecijalizacijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Pacijent");

                    b.Navigation("Specijalizacija");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Doktor", b =>
                {
                    b.Navigation("Termini");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Korisnik", b =>
                {
                    b.Navigation("Doktor")
                        .IsRequired();

                    b.Navigation("Pacijent")
                        .IsRequired();
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Pacijent", b =>
                {
                    b.Navigation("Termini");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Pregled", b =>
                {
                    b.Navigation("Dijagnoza");
                });

            modelBuilder.Entity("Zdravstvo.Core.Entities.Ustanova", b =>
                {
                    b.Navigation("Doktori");

                    b.Navigation("Termini");
                });
#pragma warning restore 612, 618
        }
    }
}
